console.log("This is loaded from external js");
var name = "Tyler Bennett";
var school = "CMVS";
var hobby = "Video Games";
console.log(`Name: ${name}`);
console.log(`School: ${school}`);
console.log(`Hobbies: ${hobby}`);
document.getElementById("name").innerHTML = "<b>Name: </b>"+name;
document.getElementById("school").innerHTML = "<b>School: </b>"+school;
document.getElementById("hobby").innerHTML = "<b>Hobby: </b>"+hobby;
