console.log("This is loaded from external js");
alert("This is an alert!");
var name = prompt("What is your name?");
var school = prompt("What school do you go to?");
var hobby = prompt("What do you like to do?");
console.log(`Name: ${name}`);
console.log(`School: ${school}`);
console.log(`Hobbies: ${hobby}`);
document.getElementById("name").innerHTML = "<b>Name: </b>"+name;
document.getElementById("school").innerHTML = "<b>School: </b>"+school;
document.getElementById("hobby").innerHTML = "<b>Hobby: </b>"+hobby;
